server:
  port: 9191
  
spring:  application:    name: API-Gateway  cloud:    gateway:      routes:
       - id: Subscription-SERVICE
         uri: lb://Subscription-SERVICE
         predicates :
         - Path=/subscription/**
         filters:
           - name: CircuitBreaker
             args:
               name: Subscription-SERVICE
               fallbackuri: forward:/subscriptionServiceFallBack
                  - id: BOOK-SERVICE
         uri: lb://BOOK-SERVICE         predicates :
         - Path=/books/**
         filters:
              - name: CircuitBreaker
                args:
                  name: BOOK-SERVICE
                  fallbackuri: forward:/bookServiceFallBack
               
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
       
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream    
    

    